<?php
/**
 * TL_ROOT/system/modules/breadcrumbtemplate/languages/de/tl_module.php 
 * 
 * Contao extension: breadcrumbtemplate 1.0.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy 2012 Helmut Schottmüller 
 * License   : LGPL 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['breadcrumbTpl']['0'] = "Navigationspfadtemplate";
$GLOBALS['TL_LANG']['tl_module']['breadcrumbTpl']['1'] = "Hier können Sie das Navigationspfadtemplate auswählen.";
 
?>
